### ISSUE TITLE
Illegal app, Can not found app.

### ISSUE THREAD

**Issue by sanjaygupta1234** [aliyun/aliyun-openapi-php-sdk#10]
Hello There I have a account on alicloud, I am new for this. I have been download the sdk and using my accessKeyId  and accessSecret, I am able to run script but it is not clear that how I can get a valid appKey to run. 

PushDemo.php flile in aliyun-openapi-php-sdk-master / aliyun-php-sdk-demo folder, I am using default 
$appKey = 123456; and its giving error... 

stdClass Object
(
    [RequestId] => 6014E639-7E63-495B-BE8C-77DED733AD1A
    [HostId] => cloudpush.aliyuncs.com
    [Code] => Illegal app
    [Message] => Can not found app.
)

Fatal error:  Uncaught exception 'ClientException' with message 'Can not found app.' in C:\xampp\htdocs\aliyun-openapi-php-sdk-master\aliyun-php-sdk-core\DefaultAcsClient.php:109
Stack trace:
#0 C:\xampp\htdocs\aliyun-openapi-php-sdk-master\aliyun-php-sdk-core\DefaultAcsClient.php(36): DefaultAcsClient->buildApiException(Object(stdClass), 402)
#1 C:\xampp\htdocs\aliyun-openapi-php-sdk-master\aliyun-php-sdk-demo\PushDemo.php(41): DefaultAcsClient->getAcsResponse(Object(Push\Request\V20150827\PushNoticeToAndroidRequest))
#2 {main}

  thrown in C:\xampp\htdocs\aliyun-openapi-php-sdk-master\aliyun-php-sdk-core\DefaultAcsClient.php on line 109

How I can get a valid appKey?

**Comment by ElaineFei** [comment]
Hello, I'm sorry, I was not able to reply your question in time. Next, Alibaba Cloud official technical staff will provide you with efficient support. If you still have questions that are not answered, please resubmit the issue. Thank you for your attention on Alibaba Cloud and Alibaba Cloud SDK.
