### ISSUE TITLE
这里这么多的sdk，我都不知道我所要的对应哪个sdk

### ISSUE THREAD

**Issue by BuTingBa** [aliyun/aliyun-openapi-php-sdk#100]
这里这么多的sdk，我都不知道我所要的对应哪个sdk，能不能给个列表？

**Comment by ghost** [comment]
我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK
https://github.com/aliyun/openapi-sdk-php/


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK:

https://github.com/aliyun/openapi-sdk-php

**Comment by BuTingBa** [comment]
要是我能用新版本我还来用老版本干什么？？？

**Comment by ghost** [comment]
请问根据产品的代码找到相应的文件引入，注：并不支持所有的产品，如果找不到，请在阿里云控制台提工单由产品服务。

**Comment by lszxlong** [comment]
官网下的例子，跟这个版本还对应不起来，能不能搞成统一的啊

**Comment by ghost** [comment]
> 官网下的例子，跟这个版本还对应不起来，能不能搞成统一的啊

旧版SDK已经不再维护了

**Comment by ghost** [comment]
> 请问根据产品的代码找到相应的文件引入，注：并不支持所有的产品，如果找不到，请在阿里云控制台提工单由产品服务。

如果没有其他问题，此 issue 将被关闭。
