### ISSUE TITLE
EndpointConfig.php line 28：Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by huang906691** [aliyun/aliyun-openapi-php-sdk#102]
`include_once 'aliyuncs/aliyun-php-sdk-core/Config.php';`
引入config文件即报错，原因是EndpointConfig.php文件第一行未引入endpoints.xml文件，正确的写法应该是
`$endpoint_filename = __DIR__ . DIRECTORY_SEPARATOR.'endpoints.xml'`

**Comment by ghost** [comment]
请问是在哪个产品文档看到的demo？请回复地址，我们会反馈给文档部门。

**Comment by huang906691** [comment]
https://help.aliyun.com/document_detail/50180.html?spm=a2c4g.11174283.6.752.5cbb7487TYg5Le

使用内容安全SDK时报的错，不过aliyun-php-sdk-core/Config.php这个文件看起来是整个PHP SDK所使用的核心配置文件，其他SDK使用的时候也会报错吧。

**Comment by ghost** [comment]
> https://help.aliyun.com/document_detail/50180.html?spm=a2c4g.11174283.6.752.5cbb7487TYg5Le
> 
> 使用内容安全SDK时报的错，不过aliyun-php-sdk-core/Config.php这个文件看起来是整个PHP SDK所使用的核心配置文件，其他SDK使用的时候也会报错吧。

这个版本的SDK已经废弃许久，请使用最新版本的SDK : https://github.com/aliyun/openapi-sdk-php
