### ISSUE TITLE
从官网过来的说下载这个版本使用，这里又说明已经弃用，这到底是用哪个SDK?

### ISSUE THREAD

**Issue by anywn3773** [aliyun/aliyun-openapi-php-sdk#108]
从官网过来的说下载这个版本使用，这里又说明已经弃用，这到底是用哪个SDK?

**Comment by AxiosLeo** [comment]
请看主页的 [readme](https://github.com/aliyun/aliyun-openapi-php-sdk/blob/master/README.md) 里的“已废弃声明”，里面有支持 Composer 的新版 SDK 的链接地址。

还有，可以贴下让您指向这里的官网链接地址吗
