### ISSUE TITLE
文档维护的真的比较差

### ISSUE THREAD

**Issue by 350050183** [aliyun/aliyun-openapi-php-sdk#20]
这个接口 https://help.aliyun.com/document_detail/35412.html?spm=5176.doc48230.6.564.eRn8Gr

如果设置Version为 2016-11-01 SDK 提示 Specified api is not found, please check your url and method. 但浏览器直接访问提示：Specified parameter Version is not valid.

如果设置Version为 2014-11-11 可以通过浏览器直接获取正确结果，但sdk提示Specified parameter Version is not valid.

这是几个意思啊？

文档上为何不说明下各个接口所需要的版本号呢？让用户去猜？

**Comment by jiangqx** [comment]
确实，文档上说只有一个必填项目，结果，填了一个参数后，接着又要上传另外的参数，感觉进入到了一个迷宫。

**Comment by conan425** [comment]
@350050183 感谢您关注阿里云PHP SDK，您的反馈已经收到，我们将尽快完善

**Comment by ElaineFei** [comment]
您好，请您暂时参见：https://help.aliyun.com/document_detail/53111.html

我们将尽快完善

**Comment by ElaineFei** [comment]
您好，关于文档的反馈我们已经收到了，这里先把issues关了，我们将尽快完善。

您有任何问题可以另起issues，或者加入阿里云官方SDK钉钉群11771185 直接与我们沟通~ 更方便。感谢关注，感谢支持。
