### ISSUE TITLE
什么时候上composer

### ISSUE THREAD

**Issue by gtspoon** [aliyun/aliyun-openapi-php-sdk#24]
什么时候上composer？方便对包的引入啊

**Comment by xutl** [comment]
试试 https://github.com/aliyunapi/guzzle-subscriber

**Comment by codBo** [comment]
什么时候像aws一样弄成composer的

**Comment by holox** [comment]
估计没戏了。

**Comment by tourze** [comment]
希望官方快点支持啊

**Comment by wudi** [comment]
Composer 全支持
https://github.com/anchnet/aliyun-openapi-php-sdk
https://packagist.org/packages/anchnet/aliyun-openapi-php-sdk

**Comment by radmanz** [comment]
composer support please... all other forks are not maintained! 
n00bz!!!!

**Comment by conan425** [comment]
已经在计划中了，谢谢大家的关注，之前给大家带来不便很抱歉

**Comment by tourze** [comment]
请求这个计划什么时候上？

**Comment by ghost** [comment]
> 什么时候上composer？方便对包的引入啊

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> 试试 https://github.com/aliyunapi/guzzle-subscriber

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> 什么时候像aws一样弄成composer的

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> 估计没戏了。

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> 希望官方快点支持啊

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> composer support please... all other forks are not maintained!
> n00bz!!!!

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by ghost** [comment]
> 请求这个计划什么时候上？

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
