### ISSUE TITLE
能否不在sdk中修改php的默认时区

### ISSUE THREAD

**Issue by shennyLee** [aliyun/aliyun-openapi-php-sdk#26]
在RoaAcsRequest的82行和RpcAcsRequest的63行
我理解你们需要获取一个utc的格式化时间，但是使用gmdate('Y-m-d\TH:i:s\Z')就好了呀^.^

**Comment by anjestar** [comment]
是啊。我们自己在后面用到时间的，这个影响很大啊。

**Comment by sinri** [comment]
我魔改了sdk全改成gmdate了，不过pull request还没有处理。

**Comment by laodaxyz** [comment]
竟然在二三个地方，写死了时区设置，想用正常时间都麻烦，郁闷

**Comment by banfg56** [comment]
果真是这样。。。。

**Comment by conan425** [comment]
@shennyLee 感谢您关注阿里云PHP SDK，目前最新版本已经修复了这个问题，谢谢！
