### ISSUE TITLE
建议增加composer安装支持

### ISSUE THREAD

**Issue by zoujingli** [aliyun/aliyun-openapi-php-sdk#27]
建议增加composer安装支持

**Comment by zhkzyth** [comment]
+1

**Comment by 123Daoxyz** [comment]
完全无法接受没有composer的支持....

**Comment by shikuntian** [comment]
完全无法接受没有composer的支持,能不能快点支持啊。现在开发起来太麻烦了，一找问题，好多都是依赖和conf的原因。

**Comment by likyh** [comment]
+1

**Comment by shehuaqigai** [comment]
composer require aliyun/openapi-php-sdk
里面的完全不一样，用你的推送还真是很痛苦，整合到框架里面真是费劲

**Comment by jasonencode** [comment]
"repositories": [
        {
            "type": "package",
            "package": {
                "name": "aliyun/aliyun-openapi-php-sdk",
                "version": "dev-master",
                "source": {
                    "url": "https://github.com/aliyun/aliyun-openapi-php-sdk",
                    "type": "git",
                    "reference": "master"
                },
                "autoload": {
                    "classmap": ["/"]
                }
            }
        }
    ]
composer 可以引用，但是出现各种各样的问题

**Comment by likyh** [comment]
因为这根本不是同一份东西……

**Comment by wudi** [comment]
Composer 版本推荐 https://github.com/anchnet/aliyun-openapi-php-sdk

**Comment by xutl** [comment]
https://github.com/aliyunapi/guzzle-subscriber

**Comment by bitqiu** [comment]
不支持 composer 真 费劲

**Comment by radmanz** [comment]
Aliyun are really behind in package management technology!
Hurry up and support composer!

**Comment by conan425** [comment]
已经在计划中了，谢谢大家的关注，之前给大家带来不便很抱歉

**Comment by AxiosLeo** [comment]
@bitqiu @cjango @zoujingli  我最近在开发支持composer版的阿里云sdk，目前已开发完成OSS、VOD、CDN、SMS、MTS的SDK，欢迎关注。

**Comment by AxiosLeo** [comment]
@bitqiu @cjango @zoujingli  
项目地址 [AxiosCros/aliyun-sdk](https://github.com/AxiosCros/aliyun-sdk)

**Comment by Leslie1sMe** [comment]
composer require leslie/aliyun-sts了解一下？

**Comment by lindaolan** [comment]
现在都2018年8月底了，还没支持，怎么搞？

**Comment by xiaomlove** [comment]
真的不想说粗口话，但也实在是很不方便，有那么难吗？

**Comment by Obacm** [comment]
是的，还没支持

**Comment by mitoop** [comment]
有具体的计划时间吗 今天 2018-12-21

**Comment by likyh** [comment]
@mitoop 想啥呢，从之前的sdk开始，到现在起码5年了…… 感觉php就是后妈养的，mns的sdk为了发起http请求，直接引入了一个百来个文件的框架………………

**Comment by wesley-firewalla** [comment]
阿里的开发人员这么菜，连composer支持到现在都搞不来

**Comment by xiaomlove** [comment]
越到后边代码量越大支持难度越大。。。估计是没戏了，这位 @conan425 估计已经离职。我是要哪个就下载哪个，手动include core的Autoloader解决的。

**Comment by huiwanggo** [comment]
马上2019了！！！！还没支持composer。。。

**Comment by qbhy** [comment]
要不把我招进去给这个sdk添加下composer支持咯

**Comment by JacksonTian** [comment]
@qbhy 求简历。

**Comment by JacksonTian** [comment]
我们刚刚 release 了一个支持 composer 的试用版：https://github.com/aliyun/openapi-sdk-php-client 。
除了 composer 的支持外，我们还对核心库提供了高覆盖率的单元测试，以此保障整个项目的可维护性和稳定性。

因为还在打磨中，因此处于 0.x 的状态，欢迎大家试用并提出宝贵的意见。

再次感谢大家。如果有同学愿意加入阿里云来改进阿里云的 SDK，欢迎投递简历给我。

**Comment by huiwanggo** [comment]
@JacksonTian  太菜了，不敢不敢。大佬加油，我先尝鲜。

**Comment by ghost** [comment]
我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php

**Comment by Leslie1sMe** [comment]
不是说有钉钉群可以交流吗

**Comment by ghost** [comment]
> 不是说有钉钉群可以交流吗


我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：
https://github.com/aliyun/openapi-sdk-php/blob/master/README-CN.md


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK:
https://github.com/aliyun/openapi-sdk-php


群号：23178217

**Comment by ghost** [comment]
> > 不是说有钉钉群可以交流吗
> 
> 我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：
> https://github.com/aliyun/openapi-sdk-php/blob/master/README-CN.md
> 
> We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK:
> https://github.com/aliyun/openapi-sdk-php
> 
> PHP 社区群群号：23178217
