### ISSUE TITLE
gmdate 的合理使用

### ISSUE THREAD

**Issue by shiny** [aliyun/aliyun-openapi-php-sdk#30]
`aliyun-openapi-php-sdk/aliyun-php-sdk-core/RpcAcsRequest.php`

62 行
```
date_default_timezone_set("GMT");
$apiParams["Timestamp"] = date($this->dateTimeFormat);
```

可以改成
```
$apiParams["Timestamp"] = gmdate($this->dateTimeFormat);
```

gmdate 的说明
> 同 date() 函数完全一样，只除了返回的时间是格林威治标准时（GMT）

http://php.net/manual/zh/function.gmdate.php

原来的用法会带来 side-effects。

**Comment by conan425** [comment]
@shiny 感谢您关注阿里云PHP SDK，目前最新版本已经修改了这个问题，谢谢！
