### ISSUE TITLE
DefaultAcsClient 逻辑错误

### ISSUE THREAD

**Issue by abramdev** [aliyun/aliyun-openapi-php-sdk#33]
![qq 20170904011951](https://user-images.githubusercontent.com/2335683/30005176-35a05f5a-910f-11e7-8cab-ebb2d241e958.png)

你们确定测试了吗？

**Comment by devtoby** [comment]
虽然这不是一个漂亮的写法。。。但怎么会是逻辑错误呢，$domain == null 就是判断如果没定义的处理逻辑。
