### ISSUE TITLE
第一次的请求有什么用处，注释了也正常执行

### ISSUE THREAD

**Issue by laodaxyz** [aliyun/aliyun-openapi-php-sdk#37]
1，2017-09-22 01:53:54: url: http://location.aliyuncs.com/?Id=cn-shanghai&ServiceCode=live&Type=openAPI&RegionId=cn-hangzhou&AccessKeyId=.*&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureVersion=1.0&SignatureNonce=.*&Timestamp=2017-09-22T01%3A53%3A54Z&Action=DescribeEndpoints&Version=2015-06-12&Signature=ip.*

2，2017-09-22 01:53:54: url: http://live.aliyuncs.com/: postFields: {"DomainName":"livetest.hefantv.com","RegionId":"cn-shanghai","AccessKeyId":".*","Format":"JSON","SignatureMethod":"HMAC-SHA1","SignatureVersion":"1.0","SignatureNonce":".*","Timestamp":"2017-09-22T01:53:54Z","Action":"DescribeLiveMixConfig","Version":"2016-11-01","Signature":".*"}

在核心包httpHelper写了日志

第一次的请求有什么用处，注释了也正常执行？

**Comment by conan425** [comment]
@laodaxyz 这是SDK中自动寻址的逻辑，由于每个产品线在各个区域的域名可能是不一样的，所以SDK要先通过RegionId去寻找域名然后并缓存起来，在缓存有效期内只执行一次，谢谢您的关注。
