### ISSUE TITLE
在aliyun-php-sdk-core/DefaultAcsClient.php中当出现需要重试的时候会有bug

### ISSUE THREAD

**Issue by luwm** [aliyun/aliyun-openapi-php-sdk#39]
当初次请求是500以及以上的状态码会触发重试，当重试的请求符合count($request->getDomainParameter())>0时不应该是
 $httpResponse = HttpHelper::curl($requestUrl, $request->getDomainParameter(), $request->getHeaders());
而应该是
$httpResponse = HttpHelper::curl($requestUrl, $request->getMethod(), $request->getDomainParameter(), $request->getHeaders());

**Comment by wudi** [comment]
Fix 4663e5f9fbf68cfedecd69e6c19de4fc66e8e46c
推荐使用 https://github.com/anchnet/aliyun-openapi-php-sdk
Composer 全支持

**Comment by devtoby** [comment]
@eaglewu 你这个为什么不放到一个大的命名空间下呢？

**Comment by ghost** [comment]
已解决
