### ISSUE TITLE
Ecs\DescribeInstancesRequest 中 IP地址的辨别遇到问题……

### ISSUE THREAD

**Issue by ghost** [aliyun/aliyun-openapi-php-sdk#4]
您好，
我的想法试通过它查询对应的IP地址，在工单（CA6GD5A）中也有详细的说明，这里把我认为核心的错误内容发给您参考：

我的相关代码如下：

``` php
//...
//Line 18
$request = new Ecs\DescribeInstancesRequest();
//...
//Line 24
$request->setPrivateIpAddress($IP_ADDRESS);
//...
//Line 31
$result = $client->getAcsResponse($request);
//...
```

$IP_ADDRESS是一个String型的IP地址变量（比如101.200.123.45）

执行后发生如下错误：
**Fatal error**:
Uncaught exception 'ClientException' with message 'InvalidParameter.PrivateIpAddresses.' in /home/www/ecs-test/aliyun-sdk/aliyun-php-sdk-core/DefaultAcsClient.php:98

**Stack trace**:

**#0** /home/www/ecs-test/aliyun-sdk/aliyun-php-sdk-core/**DefaultAcsClient.php(35)**: DefaultAcsClient->buildApiException(Object(stdClass), 400)

**#1** /home/www/ecs-test/aliyun-sdk/**test.php(31)**: DefaultAcsClient->getAcsResponse(Object(Ecs\Request\V20140526\DescribeInstancesRequest)) 

**#2** {main} thrown in /home/www/ecs-test/aliyun-sdk/aliyun-php-sdk-core/**DefaultAcsClient.php on line 98** 

跟踪栈错误到**test.php**的31行执行完成前就停止了，所以肯定没有返回_RequestID_给你们做参考。

这个具体的我没有跟踪调查DefaultAcsClient.php的35和98行内容，先把错误po出来，按照你们API的介绍，按说_$privateIpAddresses_应该是String型的，但是带入之后就错了，如果有任何新的发现，我会跟进发出来的

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
