### ISSUE TITLE
这个SDK真是烂的极致了

### ISSUE THREAD

**Issue by moookey** [aliyun/aliyun-openapi-php-sdk#41]
看起来不像是阿里云的员工写的。么见过如此结构层次烂的代码。
况且连个文档都没有，鬼知道怎么用啊？git来的工程师是不是觉得所有人的脑子跟你的脑子是一模一样的，连个文档都没有就知道怎么用？
不建议阿里云雇佣这种第三方的垃圾工程师应付了事，败坏阿里云的名誉。
烂，烂，没有更烂了。

**Comment by xutl** [comment]
https://github.com/aliyunapi/guzzle-subscriber

**Comment by conan425** [comment]
@moookey 感谢您关注阿里云PHP SDK，您的反馈已经收到，我们将尽快完善

**Comment by huangdengpan** [comment]
然而朕已经花了2天搞好了。。。。，本来只需要10分钟的码，花两天猜测开发者的代码意图。
