### ISSUE TITLE
我想使用ROS

### ISSUE THREAD

**Issue by SnhrK** [aliyun/aliyun-openapi-php-sdk#42]
我直接添加了代码，但是不能用当前的`aliyun-php-sdk-core / RoaAcsRequest.php`.

**Comment by conan425** [comment]
@SnhrK 您好，请您参考阿里云ROS产品的官方Api文档，如果没有查到PHP SDK，可以通过客服或者提交工单的形式告诉我们，我们会有专门的同学去推进，谢谢！
