### ISSUE TITLE
api网关的在哪里

### ISSUE THREAD

**Issue by wetist01** [aliyun/aliyun-openapi-php-sdk#50]
api网关的sdk没出吗

**Comment by AxiosLeo** [comment]
@wetist  可以试试我在维护的这个axios/aliyun-sdk composer组件，目前API网关的sdk还在开发，可以一起来开发。核心模块基本开发完了，剩下的就是搬砖了。

[\aliyun\sdk\api\API代码](https://github.com/AxiosCros/aliyun-sdk/blob/master/library/api/API.php)

[README](https://github.com/AxiosCros/aliyun-sdk/blob/master/README.md)


使用示例：
```php
require_once __DIR__. "/../vendor/autoload.php";

$access_id = "testAccessKeyId";
$access_secret = "testAccessKeySecret";

\aliyun\sdk\Aliyun::region('cn-hangzhou');

$response = \aliyun\sdk\api\API::DescribeApiGroups()->request();

dump($response->getContent());
```

**Comment by zhikucms** [comment]
你TM整个API在哪里初始化你得说一下啊，MD，SDK就是为了减少工作时间，结果我找你初始化的地方找了半天没找到，阿里云官网上也没任何说明。你这是写给你自己看的是吧？

**Comment by ghost** [comment]
> api网关的sdk没出吗

您好，我们已经发布了包含 CloudApi（API网关）并支持 Composer 的SDK，请安装使用： https://github.com/aliyun/openapi-sdk-php

代码示例：

  $request = AlibabaCloud::cloudAPI()
                               ->v20160714()
                               ->describeRegions();

        try {
            $result = $request->request();
            self::assertArrayHasKey('Region', $result['Regions']);
        } catch (ClientException $e) {
            self::assertStringStartsWith('cURL error', $e->getErrorMessage());
        }
