### ISSUE TITLE
官方为什么不出个Composer版本的呢？

### ISSUE THREAD

**Issue by pionear-layen** [aliyun/aliyun-openapi-php-sdk#51]
这样多方便啊

**Comment by AxiosLeo** [comment]
可能是历史遗留问题吧。如果要支持composer，之前的代码都要重构。

**Comment by cnsaturn** [comment]
+1

**Comment by sinri** [comment]
并没有什么要重构的麻烦，我们都被逼急了自己做了好多第三方composer包版本了。

**Comment by AxiosLeo** [comment]
@sinri  
大公司流程一般都固化了，没那么灵活的，所以会有很多历史遗留问题，更新换代接受新事物也很慢。

我们可以一起维护这一版，目标是打算实现阿里云全服务SDK的。
https://github.com/AxiosCros/aliyun-sdk

**Comment by sinri** [comment]
@AxiosCros 
仰视大佬
