### ISSUE TITLE
aliyun-openapi-php-sdk 要怎么用来着

### ISSUE THREAD

**Issue by pionear-layen** [aliyun/aliyun-openapi-php-sdk#52]
我想要使用域名的SDK,SDK的使用能不能举个例子呀？

**Comment by AxiosLeo** [comment]
@layen520   可以试试我在维护的aliyun-sdk。

[aliyun-sdk/blob/master/example/cdn.php](https://github.com/AxiosCros/aliyun-sdk/blob/master/example/cdn.php)
这个是使用示例
