### ISSUE TITLE
core没有namespace

### ISSUE THREAD

**Issue by jianboolee** [aliyun/aliyun-openapi-php-sdk#53]
core中没有namespace，在yaf框架下用会报autoload警告。

composer版目前不支持sts，所以也用不了。

其它项目例如OSS都用了namespace，不知道core为什么没用。

现在的方案是给改core下的文件，加入namespace。

不知道还有没有其它解决方案

**Comment by AxiosLeo** [comment]
@jianboolee  
可以试试我维护的这个
https://github.com/AxiosCros/aliyun-sdk

**Comment by ghost** [comment]
> core中没有namespace，在yaf框架下用会报autoload警告。
> 
> composer版目前不支持sts，所以也用不了。
> 
> 其它项目例如OSS都用了namespace，不知道core为什么没用。
> 
> 现在的方案是给改core下的文件，加入namespace。
> 
> 不知道还有没有其它解决方案

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
