### ISSUE TITLE
请问openapi 内为何没有集成 OSS 和SMS 的SDK 呐？

### ISSUE THREAD

**Issue by msxiehui** [aliyun/aliyun-openapi-php-sdk#57]

**Comment by AxiosLeo** [comment]
@msxiehui 
签名验证机制和请求方式不太一样，core不通用

可以试试这个，有oss和sms的
https://github.com/AxiosCros/aliyun-sdk

**Comment by Qingtang-SDK** [comment]
我们将在未来版本中集成阿里云所有产品，谢谢！

**Comment by ghost** [comment]
OSS 在将来继承，目前已经支持 sms，Dysmsapi

**Comment by ghost** [comment]
我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php/blob/master/README-CN.md


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
