### ISSUE TITLE
Green\Request\V20160224\ImageDetectionRequest

### ISSUE THREAD

**Issue by krwu** [aliyun/aliyun-openapi-php-sdk#6]
直接用API文档的示例代码，替换了accessKey，accessSecret和Image Url，报SignatureNotMatch错误。

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
