### ISSUE TITLE
强烈要求支持composer安装

### ISSUE THREAD

**Issue by jxlwqq** [aliyun/aliyun-openapi-php-sdk#60]
都什么年代了，居然不支持composer包安装，这个sdk写的真烂。

**Comment by AxiosLeo** [comment]
@jxlwqq  这个代码库好像官方没人维护的，你的反映估计没人搭理的。
实在要用composer版的话，我们可以一起维护这个sdk
https://github.com/AxiosCros/aliyun-sdk

**Comment by cha0ran** [comment]
不支持composer确实有点坑。期待支持

**Comment by wskeee** [comment]
支持一下2楼

**Comment by AxiosLeo** [comment]
@wskeee 
那就一起来commit呗，争取做的比官方这个还好。
我现在就只做了一些主流阿里云服务的sdk，还有好些不常用的没做呢。
不过，核心组件基本比较完善了，剩下的就是看需求搬砖咯~
