### ISSUE TITLE
存在非安全的数组查询

### ISSUE THREAD

**Issue by sinri** [aliyun/aliyun-openapi-php-sdk#65]
遇到了一个Notice。

> PHP Notice:  Undefined index: cn-hangzhou#Rds in D:\code\tianwen\vendor\sinri\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82

源代码

```php
private function checkCacheIsExpire($key)
    {
        $lastClearTime = self::$lastClearTimePerProduct[$key];
        if ($lastClearTime == null) {
            $lastClearTime = time();
            self::$lastClearTimePerProduct[$key] = $lastClearTime;
        }
// ...
```

里面` $lastClearTime = self::$lastClearTimePerProduct[$key];` 应该先观测isset或者empty，或者直接加@。

**Comment by ghost** [comment]
此问题已解决
