### ISSUE TITLE
导播服务 接口文档和sdk能同步一下吗？

### ISSUE THREAD

**Issue by smallwhale** [aliyun/aliyun-openapi-php-sdk#67]
sdk中   VideoLayer 中参数 fillMode ，FixedDelayDuration 什么含义？对应值是什么？让用户猜着来写吗？

**Comment by Qingtang-SDK** [comment]
感谢您的反馈！

**Comment by ghost** [comment]
> sdk中 VideoLayer 中参数 fillMode ，FixedDelayDuration 什么含义？对应值是什么？让用户猜着来写吗？

您好，请浏览：https://help.aliyun.com/document_detail/60268.html
