### ISSUE TITLE
调用SDK报错

### ISSUE THREAD

**Issue by wab5168** [aliyun/aliyun-openapi-php-sdk#7]
调用阿里绿网的鉴黄api，按照说明配置好后，运行报
Fatal error: Uncaught exception 'ClientException' in /var/www/aliyun/aliyun-php-sdk-core/DefaultAcsClient.php:108 Stack trace: #0 /var/www/aliyun/aliyun-php-sdk-core/DefaultAcsClient.php(35): DefaultAcsClient->buildApiException('<?xml version='...', 400) #1 /var/www/aliyun/Demo.php(10): DefaultAcsClient->getAcsResponse(Object(Green\Request\V20160224\ImageDetectionRequest)) #2 {main} thrown in /var/www/aliyun/aliyun-php-sdk-core/DefaultAcsClient.php on line 108

然后进行断点调试，显示SignatureNotMatch 错误

**Comment by wab5168** [comment]
报错

**Comment by jinzigui** [comment]
怎么解决。。。我也是这个错误。。。

**Comment by superlifebuoy** [comment]
测试代码加上
$request->setAcceptFormat("JSON");
$request->addHeader("Content-Type", "application/json");
尝试一下？

**Comment by jinzigui** [comment]
可以了耶，谢谢你的帮助哈！ @superlifebuoy

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
