### ISSUE TITLE
composer 使用教程

### ISSUE THREAD

**Issue by xiaohuilam** [aliyun/aliyun-openapi-php-sdk#71]
在你的 composer.json 的 `autoload` 添加如下的 `classmap`
```json
"路径/aliyun-php-sdk/aliyun-php-sdk-core"
```

在你的 composer.json 的 `autoload` 添加如下的 `psr-4`，此处以 vod sdk为例
```json
"vod\\": "路径/aliyun-php-sdk/aliyun-php-sdk-vod/vod/"
```

然后执行 `composer dump-autoload`.
使用你的代码，可能会报 ENABLE_HTTP_PROXY 配置文件未加载的错。你可以把 `if(ENABLE_HTTP_PROXY)` 改成 `if(defined('ENABLE_HTTP_PROXY') && ENABLE_HTTP_PROXY)`

**Comment by lindaolan** [comment]
$accessKeyId = "aaa";
        $accessSecret = "bbb";
        $iClientProfile = DefaultProfile::getProfile("cn-shanghai", $accessKeyId, $accessSecret);
        $client = new DefaultAcsClient($iClientProfile);

        $request = new Iot\PubRequest();
        $request->setProductKey("ccc"); //productKey
        $request->setMessageContent("aGVsbG93b3JsZA="); //hello world Base64 String.
        $request->setTopicFullName("/ccc/DeviceName/get"); //消息发送到的Topic全名.
        try {
            $response = $client->getAcsResponse($request);
            if ($response->Success) {
                $response = "true";
            } else {
                $response = json_encode($response);
            }
        } catch (\Exception $e) {
            $response = "ExceptionCode:" . $e->getCode() . ", ExceptionMsg:" . $e->getMessage();
        }
	var_dump($response);

运行结果：ExceptionCode:0, ExceptionMsg:Can not find endpoint to access.

**Comment by lindaolan** [comment]
$accessKeyId = "aaa";
    $accessSecret = "bbb";
    $iClientProfile = DefaultProfile::getProfile("cn-shanghai", $accessKeyId, $accessSecret);
    $client = new DefaultAcsClient($iClientProfile);

    $request = new Iot\PubRequest();
    $request->setProductKey("ccc"); //productKey
    $request->setMessageContent("aGVsbG93b3JsZA="); //hello world Base64 String.
    $request->setTopicFullName("/ccc/DeviceName/get"); //消息发送到的Topic全名.
    try {
        $response = $client->getAcsResponse($request);
        if ($response->Success) {
            $response = "true";
        } else {
            $response = json_encode($response);
        }
    } catch (\Exception $e) {
        $response = "ExceptionCode:" . $e->getCode() . ", ExceptionMsg:" . $e->getMessage();
    }
var_dump($response);

运行结果：ExceptionCode:0, ExceptionMsg:Can not find endpoint to access.

**Comment by Qingtang-SDK** [comment]
感谢！

**Comment by ghost** [comment]
我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
