### ISSUE TITLE
为什么java的SDK有Maven版的，php的就没有Composer版的？

### ISSUE THREAD

**Issue by MukuroSama** [aliyun/aliyun-openapi-php-sdk#72]
感觉受到了歧视，哈哈。
求快点支持Composer啊！

**Comment by Qingtang-SDK** [comment]
感谢反馈！

**Comment by ghost** [comment]
> 感觉受到了歧视，哈哈。
> 求快点支持Composer啊！

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
