### ISSUE TITLE
php查看转换文档提示Notice: Undefined index: cn-beijing#imm in C:\phpStudy\PHPTutorial\WWW\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82

### ISSUE THREAD

**Issue by shlzr** [aliyun/aliyun-openapi-php-sdk#75]
提示这个错Notice: Undefined index: cn-beijing#imm in C:\phpStudy\PHPTutorial\WWW\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82
我们框架中有错就不会执行 
请问提示这个是什么原因呢

**Comment by shlzr** [comment]
$client = new DefaultAcsClient($iClientProfile);
        // 设置您的项目名称
        $projectName = "sanhao-client-doc-convert";
        // 创建文档转换任务
        $request = new CreateOfficeConversionTaskRequest();
        $request->setProject($projectName);
        // 设置待转换对文件OSS路径
        $request->setSrcUri("oss://sanhao-courseware/dev/15266106932273.docx");
        // 设置文件输出格式
        $request->setTgtType("jpg");
        // 设置转换后的输出路径
        $request->setTgtUri("oss://sanhao-client-doc-convert/dev/");
        $response = $client->getAcsResponse($request);
//        return $response;这一步可以打印出东西
        //查看转换结果
        $maxRetryCount = 30;
        // 设置每次轮询的间隔
        $retryDelay = 1;
        $request = new GetOfficeConversionTaskRequest();
        $request->setTaskId($response->TaskId);
        $request->setProject($projectName);
        while($maxRetryCount--){
            $response = $client->getAcsResponse($request);
//            print_r($response);
            if($response->Status != 'Running') break;
            sleep($retryDelay);
        }
        return $response;这一步 返回null并提示那个错误

**Comment by JacksonTian** [comment]
请问 PHP 什么版本？

**Comment by shlzr** [comment]
5.6


 




------------------



李志嵘

北京三好互动教育科技有限公司/技术研发中心



北京




 
 
 
------------------ Original ------------------
From: "Jackson Tian"; 
Date: 2018年8月21日(星期二) 下午3:50
To: "aliyun/aliyun-openapi-php-sdk"; 
Cc: "shlzr"; "Author"; 
Subject: Re: [aliyun/aliyun-openapi-php-sdk] php查看转换文档提示Notice: Undefined index: cn-beijing#imm in C:\phpStudy\PHPTutorial\WWW\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82 (#75)

 

请问 PHP 什么版本？

**Comment by shlzr** [comment]
这个问题已经解决了 谢谢
 




------------------



李志嵘

北京三好互动教育科技有限公司/技术研发中心



北京




 
 
 
------------------ Original ------------------
From: "Jackson Tian"; 
Date: 2018年8月21日(星期二) 下午3:50
To: "aliyun/aliyun-openapi-php-sdk"; 
Cc: "shlzr"; "Author"; 
Subject: Re: [aliyun/aliyun-openapi-php-sdk] php查看转换文档提示Notice: Undefined index: cn-beijing#imm in C:\phpStudy\PHPTutorial\WWW\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82 (#75)

 

请问 PHP 什么版本？

**Comment by JacksonTian** [comment]
怎么解决的？

**Comment by shlzr** [comment]
php.ini 中改成这个error_reporting = E_ALL &~E_NOTICE






































或者在报错的那个文件加上error_reporting(E_ALL^E_NOTICE);







 




------------------



李志嵘

北京三好互动教育科技有限公司/技术研发中心



北京




 
 
 
------------------ Original ------------------
From: "Jackson Tian"; 
Date: 2018年8月21日(星期二) 晚上6:03
To: "aliyun/aliyun-openapi-php-sdk"; 
Cc: "shlzr"; "Author"; 
Subject: Re: [aliyun/aliyun-openapi-php-sdk] php查看转换文档提示Notice: Undefined index: cn-beijing#imm in C:\phpStudy\PHPTutorial\WWW\aliyun-openapi-php-sdk\aliyun-php-sdk-core\Regions\LocationService.php on line 82 (#75)

 

怎么解决的？
