### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by lindaolan** [aliyun/aliyun-openapi-php-sdk#76]

**Comment by lindaolan** [comment]
跪求

**Comment by lindaolan** [comment]
说计划了，半年过去了都还没，还要等到什么时候？

**Comment by AxiosLeo** [comment]
@lindaolan  看你今天发了好多求composer的，要不跟我一起维护一版咋样。

项目地址 ：
https://github.com/AxiosCros/aliyun-sdk

**Comment by Qingtang-SDK** [comment]
感谢反馈！

**Comment by ghost** [comment]
> 说计划了，半年过去了都还没，还要等到什么时候？

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK：https://github.com/aliyun/openapi-sdk-php


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK: https://github.com/aliyun/openapi-sdk-php
