### ISSUE TITLE
MTS媒体处理根据媒体OSS url获取媒体信息接口时不时报Undefined index: us-west-1#Mts

### ISSUE THREAD

**Issue by zzwooc** [aliyun/aliyun-openapi-php-sdk#78]
我是美国硅谷区的OSS和媒体处理，WEB服务器也是美国硅谷区的。

通过OSS的媒体URL，用媒体处理MTS的接口获取媒体的详细信息。（媒体本身信息和转码信息等，转码是加了一个媒体处理流自动执行）

我可以肯定媒体处理流已经处理完，转码已经完成，然后调用MTS QueryMediaListByURLRequest的时候，时不时的会报Undefined index: us-west-1#Mts的错误。

之前出现过是因为 FileUrls里面的url不能是https，我改成了http，但是后来发现，还是会时不时的报错。

然后是非常频繁的报错，我加了个日志在 request前面，变成了偶尔报错。

请问是什么原因？

代码如下：

```php
$profile = DefaultProfile::getProfile($this->region, $this->key_id, $this->secret);
$client = new DefaultAcsClient($profile);

$request = new Mts\QueryMediaListByURLRequest();
$request->setProtocol('https');
$request->setAcceptFormat('JSON');

$request->setIncludePlayList(true);
$request->setIncludeMediaInfo(true);
$request->setIncludeSnapshotList(true);

$object = $this->media->object;
$file = $this->encodeByRFC3986($object);
$url = 'http://' . $this->bucket . '.' . $this->endpoint. '/' . $file;
Log::info('Get Aliyun Transcode Videos File Urls:' . $url);
$request->setFileURLs($url);

$response = $client->getAcsResponse($request);
$json = (string) json_encode($response);
Log::info('Get Aliyun Transcode Videos Response:' . $json);
$result = json_decode($json, true);
```

错误信息如下：

![image](https://user-images.githubusercontent.com/19815528/45803076-2fcb7700-bceb-11e8-9be1-a6f592dbb714.png)

**Comment by Qingtang-SDK** [comment]
感谢反馈！ 我们正在调查这个问题。

**Comment by zzwooc** [comment]
有结果没？

> 感谢反馈！ 我们正在调查这个问题。

**Comment by X-ran** [comment]
> 感谢反馈！ 我们正在调查这个问题。

请问多久能解决这个问题？重复调用的时候经常遇到同样的报错信息

**Comment by ghost** [comment]
> 有结果没？
> 
> > 感谢反馈！ 我们正在调查这个问题。

已修复，请下载最新SDK

**Comment by zzwooc** [comment]
> > 有结果没？
> > > 感谢反馈！ 我们正在调查这个问题。
> 
> 已修复，请下载最新SDK

谢谢
