### ISSUE TITLE
RDS调用报错：The operation is not permitted due to db status of instance.

### ISSUE THREAD

**Issue by ouewqa** [aliyun/aliyun-openapi-php-sdk#8]
先CreateDatabase，然后GrantAccountPrivilege

报异常：
Exception 'ClientException' with message 'The operation is not permitted due to db status of instance.'

in /www/vendor/aliyun-openapi-php-sdk/aliyun-php-sdk-core/DefaultAcsClient.php:108

我一开始怀疑是不是数据还没有生成，直接授权导致的，所以在CreateDatabase后，我sleep 10秒后再授权，还是一样的错误。

如何解决？

**Comment by ffskyfan** [comment]
呃…… 我试着sleep了60秒，然后就能正确授权了，应该是阿里后台的创建和同步的时间比较长，需要多等等

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
