### ISSUE TITLE
请问这个云解析SDK的文件对应 的是哪个api文档 UpdateBatchDomainRecords.php

### ISSUE THREAD

**Issue by stevenyangecho** [aliyun/aliyun-openapi-php-sdk#81]
aliyun-openapi-php-sdk/aliyun-php-sdk-alidns/Alidns/Request/V20150109/UpdateBatchDomainRecordsRequest.php

UpdateBatchDomainRecords,这个文件是什么作用
`	public function setRecords($records) {
		$this->records = $records;
		$this->queryParameters["Records"]=$records;
	}`
这个代码的 $records 是什么形式

有没有相关演示代码或者文档呢

在阿里云官方 api文档中,只看到这篇文档
https://help.aliyun.com/document_detail/90011.html?spm=a2c4g.11186623.6.655.565e30f5j8lKsJ
但是对应不起来

**Comment by AxiosLeo** [comment]
https://developer.aliyun.com/api 

这里有完整的阿里云服务sdk的文档

**Comment by stevenyangecho** [comment]
> https://developer.aliyun.com/api
> 
> 这里有完整的阿里云服务sdk的文档

https://help.aliyun.com/document_detail/90011.html?spm=a2c4g.11186623.6.655.524630f5vZPJTr

大哥,真的只找到一个类似的,而且里面仅有 
批量操作类型，取值：
DOMAIN_ADD：批量添加域名
DOMAIN_DEL：批量删除域名
RR_ADD：批量添加解析
RR_DEL：批量删除解析
几种,没有找到 修改UPdate 相关的

**Comment by AxiosLeo** [comment]
https://docs.aliyun.com/#/tun/dns/api-reference/batch-related&UpdateBatchDomainRecords

**Comment by stevenyangecho** [comment]
谢谢谢谢,奇怪,两个文档长的居然不一样..
