### ISSUE TITLE
多次调用报错: Undefined index: cn-shanghai#Rds

### ISSUE THREAD

**Issue by daydaygo** [aliyun/aliyun-openapi-php-sdk#82]
PHP Notice 'Undefined index: cn-shanghai#Rds'

in aliyun-openapi-php-sdk/aliyun-php-sdk-core/Regions/LocationService.php:82

**Comment by xuzhouplus** [comment]
aliyun-openapi-php-sdk/aliyun-php-sdk-core/Regions/LocationService.php
要改这个文件的82行，源代码没有判断数组中的键名是否存在

**Comment by X-ran** [comment]
> aliyun-openapi-php-sdk/aliyun-php-sdk-core/Regions/LocationService.php
> 要改这个文件的82行，源代码没有判断数组中的键名是否存在

能详细说一下吗？遇到了同样的问题不知道怎么解决
