### ISSUE TITLE
调用-阿里云交易和账单管理API -订单列表查询服务

### ISSUE THREAD

**Issue by xcpschen** [aliyun/aliyun-openapi-php-sdk#85]
1.Fatal error: Uncaught Error: Class 'BssOpenApi\Request\V20171214\QueryOrdersRequest'
(ps:在config中添加Autoloader::addAutoloadPath("aliyun-php-sdk-bssopenapi");算解决了)
2.Fatal error: Uncaught ClientException: Can not find endpoint to access.
看了异常地方，貌似无法生成调用域名节点，有点无解，那么多sdk，api文档就几句话

**Comment by wesley-firewalla** [comment]
1. 调用的地方加上这行

```php
$clientProfile->addEndpoint($regionId, $regionId, "BssOpenApi", "business.aliyuncs.com");
```

2. 通过https://page.aliyun.com/form/act522746710/index.htm 申请BSS OpenAPI公测权限。

**Comment by ghost** [comment]
最新代码已经支持该产品的自动加载，在目前版本中的域名节点，还请根据产品说明调用addEndpoint方法添加。
