### ISSUE TITLE
DescribeSlowLogRecords 传sqlid无效了

### ISSUE THREAD

**Issue by qieangel2013** [aliyun/aliyun-openapi-php-sdk#86]
escribeSlowLogRecords 传sqlid无效了

**Comment by ghost** [comment]
请描述一下详细信息

**Comment by JacksonTian** [comment]
@qieangel2013 Would you please provide more details about your problem?

**Comment by ghost** [comment]
> escribeSlowLogRecords 传sqlid无效了

I will close it. If any questions, feel free to reopen it.
