### ISSUE TITLE
release 说明还希望能及时公布，github有很多机器人工具啊

### ISSUE THREAD

**Issue by zzwooc** [aliyun/aliyun-openapi-php-sdk#88]
github有很多机器人工具啊，很多小的改动都不知道，有工具，把各种release说明公布出来，我们也能及时更新sdk啊，好多人都在等着bug修复呢，真心希望能有release说明

**Comment by ghost** [comment]
> github有很多机器人工具啊，很多小的改动都不知道，有工具，把各种release说明公布出来，我们也能及时更新sdk啊，好多人都在等着bug修复呢，真心希望能有release说明

您好，新版SDK的Release说明地址：https://github.com/aliyun/openapi-sdk-php/releases

我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK
https://github.com/aliyun/openapi-sdk-php/blob/master/README-CN.md


We have released a new SDK that supports Composer and gradually stop maintenance this version. Welcome to the new SDK:

https://github.com/aliyun/openapi-sdk-php
