### ISSUE TITLE
怎么没有有关SDK的使用的手册啊？

### ISSUE THREAD

**Issue by hwanginsitein** [aliyun/aliyun-openapi-php-sdk#9]
有没有人可以提供个地址? 我在阿里云的网站里面只看到了API怎么调用

**Comment by qhxin** [comment]
真的是唉。。。做的太差了吧。。

**Comment by benben17** [comment]
尼玛 什么都没有

**Comment by mrzeta** [comment]
我™真是服了 同样的 文档呢？网站上 叫文档么？？？？？？wtf！

**Comment by syncyao** [comment]
同求。既然都开源了，为什么感觉跟没有开差不多。git上那么多外国人，也不好意思拿出来比噻。

**Comment by ElaineFei** [comment]
您好，请参见：https://help.aliyun.com/document_detail/53111.html

**Comment by ElaineFei** [comment]
您好，关于文档的反馈我们已经收到了，这里先把issues关了，我们将尽快完善。

您有任何问题可以另起issues，或者加入阿里云官方SDK钉钉群11771185 直接与我们沟通~ 更方便。感谢关注，感谢支持。
