### ISSUE TITLE
Remove directory like V20150109

### ISSUE THREAD

**Issue by jyxjjj** [aliyun/aliyun-openapi-php-sdk#95]
You have already allocated a version like "Version: 2.0.7" and it was updated a month ago.
But why the directory name is V20150109?
It sounds like 4-5 years ago.
And there is nothing else in its parent directory.
Why don't remove it?
Even i think Git is a good tool to control these versions, especially github.
Needn't a directory any more.

**Comment by JacksonTian** [comment]
The `V20150109` is related with OpenAPI version, not a real date. One product maybe have more versions.
