### ISSUE TITLE
Location 验证不正常

### ISSUE THREAD

**Issue by BestKind** [aliyun/aliyun-openapi-php-sdk#96]
* **PHP 版本**：7.2.17
* **平台**：UNIX
* **产品名称**：`Mts`
* **产品版本**：`20140618`
* **API**：`SubmitJobsRequest`

错误信息：Error: InvalidParameter.LocationInvalid Message: The location "Input:Location" is invalid. A location name should be one of seven region:oss-cn-hangzhou,oss-cn-shanghai,oss-cn-beijing,oss-us-west-1,oss-cn-shenzhen,oss-cn-hongkong,oss-ap-southeast-1

我的相关代码
```
        $ossLocation = 'oss-cn-beijing';
        $input = [
            'Location' => $ossLocation,
            'Bucket' => $ossInputBucket,
            'Object' => $ossInputObject,
        ];
        $request->setInput(json_encode($input));
```
按照提示我这个输入的 `Location` 值应该是没有问题的，我尝试了一下发现，只有使用 `oss-cn-hangzhou` 才不会报这个错，其他的 6 个都会报错

**Comment by ghost** [comment]
> * **PHP 版本**：7.2.17
> * **平台**：UNIX
> * **产品名称**：`Mts`
> * **产品版本**：`20140618`
> * **API**：`SubmitJobsRequest`
> 
> 错误信息：Error: InvalidParameter.LocationInvalid Message: The location "Input:Location" is invalid. A location name should be one of seven region:oss-cn-hangzhou,oss-cn-shanghai,oss-cn-beijing,oss-us-west-1,oss-cn-shenzhen,oss-cn-hongkong,oss-ap-southeast-1
> 
> 我的相关代码
> 
> ```
>         $ossLocation = 'oss-cn-beijing';
>         $input = [
>             'Location' => $ossLocation,
>             'Bucket' => $ossInputBucket,
>             'Object' => $ossInputObject,
>         ];
>         $request->setInput(json_encode($input));
> ```
> 按照提示我这个输入的 `Location` 值应该是没有问题的，我尝试了一下发现，只有使用 `oss-cn-hangzhou` 才不会报这个错，其他的 6 个都会报错

请稍等。

**Comment by ghost** [comment]
> * **PHP 版本**：7.2.17
> * **平台**：UNIX
> * **产品名称**：`Mts`
> * **产品版本**：`20140618`
> * **API**：`SubmitJobsRequest`
> 
> 错误信息：Error: InvalidParameter.LocationInvalid Message: The location "Input:Location" is invalid. A location name should be one of seven region:oss-cn-hangzhou,oss-cn-shanghai,oss-cn-beijing,oss-us-west-1,oss-cn-shenzhen,oss-cn-hongkong,oss-ap-southeast-1
> 
> 我的相关代码
> 
> ```
>         $ossLocation = 'oss-cn-beijing';
>         $input = [
>             'Location' => $ossLocation,
>             'Bucket' => $ossInputBucket,
>             'Object' => $ossInputObject,
>         ];
>         $request->setInput(json_encode($input));
> ```
> 按照提示我这个输入的 `Location` 值应该是没有问题的，我尝试了一下发现，只有使用 `oss-cn-hangzhou` 才不会报这个错，其他的 6 个都会报错

您好，此为产品API返回问题，请提交工单处理。
此外，我们已经发布了新的支持Composer的SDK，本版本不再维护，请及时切换到新版本SDK：https://github.com/aliyun/openapi-sdk-php

**Comment by BestKind** [comment]
> > * **PHP 版本**：7.2.17
> > * **平台**：UNIX
> > * **产品名称**：`Mts`
> > * **产品版本**：`20140618`
> > * **API**：`SubmitJobsRequest`
> > 
> > 错误信息：Error: InvalidParameter.LocationInvalid Message: The location "Input:Location" is invalid. A location name should be one of seven region:oss-cn-hangzhou,oss-cn-shanghai,oss-cn-beijing,oss-us-west-1,oss-cn-shenzhen,oss-cn-hongkong,oss-ap-southeast-1
> > 我的相关代码
> > ```
> >         $ossLocation = 'oss-cn-beijing';
> >         $input = [
> >             'Location' => $ossLocation,
> >             'Bucket' => $ossInputBucket,
> >             'Object' => $ossInputObject,
> >         ];
> >         $request->setInput(json_encode($input));
> > ```
> > 按照提示我这个输入的 `Location` 值应该是没有问题的，我尝试了一下发现，只有使用 `oss-cn-hangzhou` 才不会报这个错，其他的 6 个都会报错
> 
> 您好，此为产品API返回问题，请提交工单处理。
> 此外，我们已经发布了新的支持Composer的SDK，本版本不再维护，请及时切换到新版本SDK：https://github.com/aliyun/openapi-sdk-php

好的

**Comment by BestKind** [comment]
@songshenzong 好的，多谢
