### ISSUE TITLE
FileAsyncScanRequest 这个怎么用的？

### ISSUE THREAD

**Issue by mantrue** [aliyun/aliyun-openapi-php-sdk#97]
* **PHP Version**:
* **Platform**:
* **Product**:
* **Product Version**:
* **API**:

**Comment by sdk-team** [comment]
> * **PHP Version**:
> * **Platform**:
> * **Product**:
> * **Product Version**:
> * **API**:

请参照官网的文档使用。
我们已经发布了支持Composer的新SDK，并逐渐停止维护本版本，欢迎使用新版SDK

https://github.com/aliyun/openapi-sdk-php/blob/master/README-CN.md
